"""
Advanced WAF Detector — TIER 1.
Fingerprints 20+ Web Application Firewalls (WAFs) using headers, status codes, and response body patterns.
Enables other modules to adjust timing and payloads to avoid blocking.
Replaces ZAP's WAF detection scripts and wafw00f functionality.
"""
from __future__ import annotations

import asyncio
import logging
import re
from dataclasses import dataclass, field
from typing import Any

import httpx
from medusa.engine.core.rate_limiter import TokenBucket
from medusa.engine.core.scope_guard import ScopeGuard
from medusa.engine.core.session import Session
from medusa.engine.core.ws_broadcaster import WSBroadcaster

__all__ = ["WAFDetector", "WAFProfile"]

logger = logging.getLogger(__name__)

# ── WAF Signatures ──────────────────────────────────────────────────────────

# (name, header_patterns, body_patterns, code_hints, bypass_hints)
WAF_SIGNATURES = [
    ("Cloudflare",
     {"server": r"cloudflare", "cf-ray": r".*"},
     [r"cloudflare-nginx", r"Cloudflare Ray ID:"], [403, 503],
     ["Case variation", "Comment injection", "HTTP/2 bypass"]),
    
    ("AWS WAF",
     {"x-amzn-requestid": r".*", "x-amz-cf-id": r".*"},
     [r"AWSWAF", r"Request blocked by AWS WAF"], [403],
     ["JSON encoding", "Header pollution"]),

    ("Akamai",
     {"server": r"AkamaiGHost", "x-akamai-transformed": r".*"},
     [r"AkamaiGHost", r"Reference #[0-9a-f\.]+"], [403],
     ["Parameter duplication", "Large payloads"]),
    
    ("ModSecurity",
     {"server": r"ModSecurity", "x-mod-security": r".*"},
     [r"ModSecurity", r"Access denied", r"mod_security"], [403, 406],
     ["Parameter pollution", "Chunked encoding", "Double URL encoding"]),

    ("Imperva / Incapsula",
     {"x-iinfo": r".*", "x-cdn": r"Incapsula"},
     [r"Incapsula", r"visid_incap"], [403],
     ["Incomplete HTTP requests", "Custom header fuzzing"]),

    ("F5 BIG-IP ASM",
     {"server": r"BigIP", "x-wa-info": r".*"},
     [r"The requested URL was rejected. Please consult with your administrator."], [200, 403],
     ["HTTP/1.0 usage", "Slowloris-style payloads"]),

    ("Barracuda",
     {"server": r"BarracudaWAF", "barra_counter_session": r".*"},
     [r"BarracudaWAF", r"Barracuda"], [403],
     ["Case-randomization", "UTF-8 encoding"]),

    ("Sucuri",
     {"x-sucuri-id": r".*", "server": r"Sucuri/Cloudproxy"},
     [r"Sucuri WebSite Firewall", r"cloudproxy"], [403],
     ["Base64 encoding", "User-Agent spoofing"]),

    ("Wordfence",
     {},
     [r"Generated by Wordfence", r"Your access to this site has been limited"], [403],
     ["Cookie obfuscation"]),

    ("FortiWeb",
     {"server": r"FortiWeb-WAF"},
     [r"FortiWeb"], [403],
     ["Multipart parsing errors"]),
]


@dataclass
class WAFProfile:
    """Detailed WAF detection result."""
    detected: bool
    vendor: str | None = None
    confidence: float = 0.0
    bypass_hints: list[str] = field(default_factory=list)
    headers: dict[str, str] = field(default_factory=list)
    status_code: int = 0


class WAFDetector:
    """
    Fingerprints WAFs by sending non-malicious and malicious probes.
    """

    def __init__(
        self,
        guard: ScopeGuard,
        bucket: TokenBucket,
        broadcaster: WSBroadcaster | None = None,
    ) -> None:
        self.guard = guard
        self.bucket = bucket
        self.broadcaster = broadcaster or WSBroadcaster()
        self._malicious_payload = "<script>alert('medusa-waf-probe')</script>"

    async def detect(self, target: str, session: Session, auth_headers: dict[str, str] | None = None) -> WAFProfile:
        """Execute WAF detection and return profile. Backward compat entry point."""
        return await self.run(target, session, auth_headers)

    async def run(self, target: str, session: Session, auth_headers: dict[str, str] | None = None) -> WAFProfile:
        """Perform active WAF fingerprinting."""
        self.guard.check(target, "web.waf_detector")
        await self.broadcaster.log(session.id, "INFO", f"[waf_detector] Probing {target} for WAFs", "waf_detector")

        profile = WAFProfile(detected=False)

        async with httpx.AsyncClient(
            verify=False, timeout=12.0,
            headers={"User-Agent": "Medusa-Scanner/1.0", **(auth_headers or {})},
            follow_redirects=True,
        ) as client:
            try:
                # 1. Normal Request (Baseline)
                async with self.bucket:
                    normal_resp = await client.get(target)
                
                # 2. Malicious Probe
                async with self.bucket:
                    probe_resp = await client.get(target, params={"q": self._malicious_payload})
                
                # 3. Analyze Headers and Body
                profile = self._analyze_responses(normal_resp, probe_resp)
                
                if profile.detected:
                    session.add_finding(
                        module="web.waf_detector",
                        target=target,
                        title=f"WAF Detected: {profile.vendor}",
                        description=(
                            f"Web Application Firewall ({profile.vendor}) detected on {target}.\n"
                            f"Confidence: {profile.confidence * 100:.0f}%\n"
                            f"Suggested Bypasses: {', '.join(profile.bypass_hints)}"
                        ),
                        severity="info",
                        tags=["waf", "recon", profile.vendor.lower() if profile.vendor else ""],
                        owasp_category="A05:2021-Security Misconfiguration"
                    )
                    await self.broadcaster.log(
                        session.id, "INFO", 
                        f"[waf_detector] CONTEXT: {profile.vendor} WAF detected. Adjusting scan strategy.", 
                        "waf_detector"
                    )
                else:
                    await self.broadcaster.log(session.id, "INFO", "[waf_detector] No WAF detected by signatures.", "waf_detector")

            except Exception as exc:
                logger.debug("WAF detection error: %s", exc)

        return profile

    def _analyze_responses(self, normal: httpx.Response, probe: httpx.Response) -> WAFProfile:
        """Internal logic to match responses against signatures."""
        headers = {k.lower(): v.lower() for k, v in probe.headers.items()}
        body = (probe.text or "").lower()
        code = probe.status_code

        # Check if probe was blocked compared to normal
        blocked = (code in (403, 406, 501, 200) and code != normal.status_code) or \
                  (code == 200 and len(probe.text) < len(normal.text) * 0.5)

        for name, h_pats, b_pats, codes, bypasses in WAF_SIGNATURES:
            confidence = 0.0
            
            # Header Match
            h_match = 0
            for h_key, h_val_pat in h_pats.items():
                if h_key.lower() in headers and re.search(h_val_pat, headers[h_key.lower()], re.I):
                    h_match += 1
            if h_pats:
                confidence += (h_match / len(h_pats)) * 0.6
            
            # Body Match
            b_match = 0
            for b_pat in b_pats:
                if re.search(b_pat, body, re.I):
                    b_match += 1
            if b_pats:
                confidence += (b_match / len(b_pats)) * 0.4

            # Status Code Hint
            if code in codes and blocked:
                confidence += 0.2
            
            if confidence > 0.4:
                return WAFProfile(
                    detected=True,
                    vendor=name,
                    confidence=min(confidence, 1.0),
                    bypass_hints=bypasses,
                    headers=dict(probe.headers),
                    status_code=code
                )
        
        # Generic Protection Match (No specific vendor)
        if blocked:
            return WAFProfile(
                detected=True,
                vendor="Generic / Unknown WAF",
                confidence=0.5,
                bypass_hints=["Generic bypass techniques"],
                status_code=code
            )

        return WAFProfile(detected=False)
